#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 7101
ENV ASPNETCORE_URLS=http://+:7101


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["./EmailWorkerService/EmailWorkerService.csproj", "EmailWorkerService/"]
COPY ["Models/Models.csproj", "Models/"]

RUN dotnet restore "EmailWorkerService/EmailWorkerService.csproj"

COPY . .
WORKDIR "/src/EmailWorkerService"
RUN dotnet build "EmailWorkerService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EmailWorkerService.csproj" -c Release -o /app
FROM base AS final
WORKDIR /app
COPY --from=publish /app .

ENTRYPOINT ["dotnet", "EmailWorkerService.dll"]

#HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
 #   CMD curl -f http://localhost/ || exit 1
